import { marketplaceCategories } from "./sectors";

export type MarketplaceProduct = {
  id: string;
  slug: string;
  name: string;
  store: string;
  category: string;
  district: string;
  price: number;
  oldPrice?: number;
  distance: number;
  rating: number;
  stock: number;
  pickup: string;
  imageUrl: string;
  description: string;
  details: string[];
};

function imageFor(query: string, lock: number) {
  return `https://loremflickr.com/900/700/${encodeURIComponent(query)}?lock=${lock}`;
}

const baseProducts: MarketplaceProduct[] = [
  {
    id: "p1",
    slug: "pinzas-pequenas-metalicas-pack-12",
    name: "Pinzas pequenas metalicas pack 12",
    store: "Ferreteria Ramblas Pro",
    category: "Ferretería y bricolaje",
    district: "Gotico",
    price: 2.95,
    oldPrice: 4.9,
    distance: 0.35,
    rating: 4.8,
    stock: 42,
    pickup: "25 min",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAyB7U9Dz5twILkqYUhIzOsBJuCC4zV6ho5Q&s",
    description: "Pack de pinzas pequenas para bricolaje ligero, manualidades, juegos infantiles y pequenas reparaciones domesticas.",
    details: ["Pack de 12 unidades", "Tamano pequeno", "Recogida rapida en tienda", "Producto en promocion"]
  },
  {
    id: "p2",
    slug: "anillo-caramelo-fresa",
    name: "Anillo de caramelo sabor fresa",
    store: "DulceRaval",
    category: "Bazar multiproducto",
    district: "Raval",
    price: 0.99,
    oldPrice: 1.8,
    distance: 0.62,
    rating: 4.7,
    stock: 68,
    pickup: "15 min",
    imageUrl: "https://www.tiendashoppi.com/cdn/shop/products/tienda-shoppi-ring-pop-min_large.jpg?v=1632072524",
    description: "Anillo de caramelo con sabor a fresa. Producto divertido para regalos, fiestas o compra rapida de barrio.",
    details: ["Sabor fresa", "Unidad individual", "Ideal para fiestas", "Oferta de la semana"]
  },
  {
    id: "p3",
    slug: "iman-premium-barcelona-skyline",
    name: "Iman premium Barcelona skyline",
    store: "Souvenirs Barcelona 92",
    category: "Souvenirs y regalos",
    district: "Born",
    price: 4.95,
    oldPrice: 6.5,
    distance: 0.9,
    rating: 4.6,
    stock: 24,
    pickup: "20 min",
    imageUrl: "https://m.media-amazon.com/images/I/619eaAmDBkL._AC_UF894,1000_QL80_.jpg",
    description: "Iman de recuerdo inspirado en el skyline de Barcelona, perfecto para turistas o regalos rapidos.",
    details: ["Diseno Barcelona", "Formato premium", "Comercio verificado", "Recogida en Born"]
  },
  {
    id: "p4",
    slug: "kit-reforma-rapida",
    name: "Kit reforma rapida: cinta, guantes y cutter",
    store: "Ferreteria Ramblas Pro",
    category: "Ferretería y bricolaje",
    district: "Gotico",
    price: 14.95,
    distance: 0.35,
    rating: 4.8,
    stock: 17,
    pickup: "30 min",
    imageUrl: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?auto=format&fit=crop&w=900&q=80",
    description: "Kit basico para pequenas reformas en casa: cinta, guantes de proteccion y cutter multiuso.",
    details: ["Incluye 3 productos", "Recomendado por JuanIAs", "Stock disponible", "Recogida hoy"]
  },
  {
    id: "p5",
    slug: "pack-oficina-libreta-boligrafos-clips",
    name: "Pack oficina libreta, boligrafos y clips",
    store: "Papereria Catalunya",
    category: "Papelería y material escolar",
    district: "Eixample",
    price: 8.75,
    oldPrice: 11.2,
    distance: 1.2,
    rating: 4.5,
    stock: 31,
    pickup: "35 min",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    description: "Pack practico de papeleria para oficina, estudio o teletrabajo con libreta, boligrafos y clips.",
    details: ["Pack ahorro", "Material oficina", "Comercio local", "Preparado en 35 minutos"]
  },
  {
    id: "p6",
    slug: "ramo-urbano-azul-amarillo",
    name: "Ramo urbano azul y amarillo",
    store: "Floristeria La Rambla",
    category: "Floristería no perecedera",
    district: "Gotico",
    price: 22.5,
    distance: 0.48,
    rating: 4.9,
    stock: 9,
    pickup: "45 min",
    imageUrl: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=900&q=80",
    description: "Ramo fresco de estilo urbano con tonos azules y amarillos, preparado por floristeria local.",
    details: ["Flores frescas", "Preparacion artesanal", "Recogida en tienda", "Unidades limitadas"]
  },
  {
    id: "p7",
    slug: "bolsa-mix-gominolas-500g",
    name: "Bolsa mix gominolas 500 g",
    store: "DulceRaval",
    category: "Bazar multiproducto",
    district: "Raval",
    price: 5.9,
    distance: 0.62,
    rating: 4.7,
    stock: 54,
    pickup: "15 min",
    imageUrl: "https://images.unsplash.com/photo-1575224300306-1b8da36134ec?auto=format&fit=crop&w=900&q=80",
    description: "Bolsa variada de gominolas de 500 gramos para fiestas, regalos o caprichos de ultima hora.",
    details: ["500 gramos", "Mix variado", "Preparacion inmediata", "Tienda cercana"]
  },
  {
    id: "p8",
    slug: "taza-ceramica-barcelona-local-edition",
    name: "Taza ceramica Barcelona local edition",
    store: "Souvenirs Barcelona 92",
    category: "Cerámica y diseño local",
    district: "Born",
    price: 9.95,
    distance: 0.9,
    rating: 4.6,
    stock: 18,
    pickup: "20 min",
    imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80",
    description: "Taza de ceramica inspirada en Barcelona, pensada para regalo local o recuerdo de viaje.",
    details: ["Ceramica", "Diseno local", "Apta para regalo", "Comercio verificado"]
  }
];

const additionalProductSeeds = [
  {
    "id": "a1",
    "slug": "postal-panoramica-barcelona",
    "name": "Postal panorámica Barcelona",
    "store": "Souvenirs Barcelona 92",
    "category": "Souvenirs y regalos",
    "district": "Raval",
    "price": 6.95,
    "distance": 0.42,
    "rating": 4.3,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Postal panorámica Barcelona product",
    "description": "Postal panorámica Barcelona disponible en comercio local de souvenirs y regalos, con recogida cercana y stock actualizado.",
    "details": ["Souvenirs y regalos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a2",
    "slug": "pack-imanes-gaudi",
    "name": "Pack imanes Gaudí",
    "store": "Souvenirs Barcelona 92",
    "category": "Souvenirs y regalos",
    "district": "Born",
    "price": 11.9,
    "distance": 0.59,
    "rating": 4.3,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Pack imanes Gaudí product",
    "description": "Pack imanes Gaudí disponible en comercio local de souvenirs y regalos, con recogida cercana y stock actualizado.",
    "details": ["Souvenirs y regalos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a3",
    "slug": "llavero-skyline-metalico",
    "name": "Llavero skyline metálico",
    "store": "Souvenirs Barcelona 92",
    "category": "Souvenirs y regalos",
    "district": "Eixample",
    "price": 3.95,
    "distance": 0.76,
    "rating": 4.4,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Llavero skyline metálico product",
    "description": "Llavero skyline metálico disponible en comercio local de souvenirs y regalos, con recogida cercana y stock actualizado.",
    "details": ["Souvenirs y regalos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a4",
    "slug": "set-brocas-pared-6-piezas",
    "name": "Set brocas pared 6 piezas",
    "store": "Ferreteria Ramblas Pro",
    "category": "Ferretería y bricolaje",
    "district": "Sant Antoni",
    "price": 13.9,
    "distance": 0.93,
    "rating": 4.5,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Set brocas pared 6 piezas product",
    "description": "Set brocas pared 6 piezas disponible en comercio local de ferretería y bricolaje, con recogida cercana y stock actualizado.",
    "details": ["Ferretería y bricolaje", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a5",
    "slug": "cinta-americana-reforzada",
    "name": "Cinta americana reforzada",
    "store": "Ferreteria Ramblas Pro",
    "category": "Ferretería y bricolaje",
    "district": "Gracia",
    "price": 21.9,
    "distance": 1.1,
    "rating": 4.5,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Cinta americana reforzada product",
    "description": "Cinta americana reforzada disponible en comercio local de ferretería y bricolaje, con recogida cercana y stock actualizado.",
    "details": ["Ferretería y bricolaje", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a6",
    "slug": "adhesivo-montaje-rapido",
    "name": "Adhesivo montaje rápido",
    "store": "Ferreteria Ramblas Pro",
    "category": "Ferretería y bricolaje",
    "district": "Barceloneta",
    "price": 6.95,
    "oldPrice": 8.2,
    "distance": 1.27,
    "rating": 4.6,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Adhesivo montaje rápido product",
    "description": "Adhesivo montaje rápido disponible en comercio local de ferretería y bricolaje, con recogida cercana y stock actualizado.",
    "details": ["Ferretería y bricolaje", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a7",
    "slug": "cuaderno-tapa-dura-a5",
    "name": "Cuaderno tapa dura A5",
    "store": "Papereria Catalunya",
    "category": "Papelería y material escolar",
    "district": "Gotico",
    "price": 8.95,
    "distance": 1.44,
    "rating": 4.7,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Cuaderno tapa dura A5 product",
    "description": "Cuaderno tapa dura A5 disponible en comercio local de papelería y material escolar, con recogida cercana y stock actualizado.",
    "details": ["Papelería y material escolar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a8",
    "slug": "pack-boligrafos-gel-colores",
    "name": "Pack bolígrafos gel colores",
    "store": "Papereria Catalunya",
    "category": "Papelería y material escolar",
    "district": "Raval",
    "price": 15.9,
    "distance": 1.61,
    "rating": 4.8,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Pack bolígrafos gel colores product",
    "description": "Pack bolígrafos gel colores disponible en comercio local de papelería y material escolar, con recogida cercana y stock actualizado.",
    "details": ["Papelería y material escolar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a9",
    "slug": "carpeta-clasificadora-acordeon",
    "name": "Carpeta clasificadora acordeón",
    "store": "Papereria Catalunya",
    "category": "Papelería y material escolar",
    "district": "Born",
    "price": 5.95,
    "distance": 1.78,
    "rating": 4.8,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Carpeta clasificadora acordeón product",
    "description": "Carpeta clasificadora acordeón disponible en comercio local de papelería y material escolar, con recogida cercana y stock actualizado.",
    "details": ["Papelería y material escolar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a10",
    "slug": "guia-ilustrada-de-barcelona",
    "name": "Guía ilustrada de Barcelona",
    "store": "Llibreria del Born",
    "category": "Librería",
    "district": "Eixample",
    "price": 23.9,
    "distance": 1.95,
    "rating": 4.9,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Guía ilustrada de Barcelona product",
    "description": "Guía ilustrada de Barcelona disponible en comercio local de librería, con recogida cercana y stock actualizado.",
    "details": ["Librería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a11",
    "slug": "novela-edicion-bolsillo",
    "name": "Novela edición bolsillo",
    "store": "Llibreria del Born",
    "category": "Librería",
    "district": "Sant Antoni",
    "price": 11.9,
    "distance": 2.12,
    "rating": 5.0,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Novela edición bolsillo product",
    "description": "Novela edición bolsillo disponible en comercio local de librería, con recogida cercana y stock actualizado.",
    "details": ["Librería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a12",
    "slug": "comic-europeo-tapa-blanda",
    "name": "Cómic europeo tapa blanda",
    "store": "Llibreria del Born",
    "category": "Librería",
    "district": "Gracia",
    "price": 18.9,
    "oldPrice": 22.3,
    "distance": 2.29,
    "rating": 4.2,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Cómic europeo tapa blanda product",
    "description": "Cómic europeo tapa blanda disponible en comercio local de librería, con recogida cercana y stock actualizado.",
    "details": ["Librería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a13",
    "slug": "panuelo-estampado-local",
    "name": "Pañuelo estampado local",
    "store": "Moda Gotic",
    "category": "Moda y complementos",
    "district": "Barceloneta",
    "price": 23.9,
    "distance": 2.46,
    "rating": 4.3,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Pañuelo estampado local product",
    "description": "Pañuelo estampado local disponible en comercio local de moda y complementos, con recogida cercana y stock actualizado.",
    "details": ["Moda y complementos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a14",
    "slug": "bolso-bandolera-urbano",
    "name": "Bolso bandolera urbano",
    "store": "Moda Gotic",
    "category": "Moda y complementos",
    "district": "Gotico",
    "price": 37.9,
    "distance": 0.23,
    "rating": 4.4,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Bolso bandolera urbano product",
    "description": "Bolso bandolera urbano disponible en comercio local de moda y complementos, con recogida cercana y stock actualizado.",
    "details": ["Moda y complementos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a15",
    "slug": "cinturon-piel-trenzada",
    "name": "Cinturón piel trenzada",
    "store": "Moda Gotic",
    "category": "Moda y complementos",
    "district": "Raval",
    "price": 10.9,
    "distance": 0.4,
    "rating": 4.4,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Cinturón piel trenzada product",
    "description": "Cinturón piel trenzada disponible en comercio local de moda y complementos, con recogida cercana y stock actualizado.",
    "details": ["Moda y complementos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a16",
    "slug": "plantillas-confort-gel",
    "name": "Plantillas confort gel",
    "store": "Zapateria Raval",
    "category": "Calzado",
    "district": "Born",
    "price": 9.95,
    "distance": 0.57,
    "rating": 4.5,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Plantillas confort gel product",
    "description": "Plantillas confort gel disponible en comercio local de calzado, con recogida cercana y stock actualizado.",
    "details": ["Calzado", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a17",
    "slug": "cordones-encerados-premium",
    "name": "Cordones encerados premium",
    "store": "Zapateria Raval",
    "category": "Calzado",
    "district": "Eixample",
    "price": 21.9,
    "distance": 0.74,
    "rating": 4.6,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Cordones encerados premium product",
    "description": "Cordones encerados premium disponible en comercio local de calzado, con recogida cercana y stock actualizado.",
    "details": ["Calzado", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a18",
    "slug": "cepillo-limpia-calzado",
    "name": "Cepillo limpia calzado",
    "store": "Zapateria Raval",
    "category": "Calzado",
    "district": "Sant Antoni",
    "price": 33.9,
    "oldPrice": 40.0,
    "distance": 0.91,
    "rating": 4.7,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Cepillo limpia calzado product",
    "description": "Cepillo limpia calzado disponible en comercio local de calzado, con recogida cercana y stock actualizado.",
    "details": ["Calzado", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a19",
    "slug": "pulsera-acero-minimalista",
    "name": "Pulsera acero minimalista",
    "store": "Bijoux Ramblas",
    "category": "Joyería y bisutería",
    "district": "Gracia",
    "price": 41.9,
    "distance": 1.08,
    "rating": 4.7,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Pulsera acero minimalista product",
    "description": "Pulsera acero minimalista disponible en comercio local de joyería y bisutería, con recogida cercana y stock actualizado.",
    "details": ["Joyería y bisutería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a20",
    "slug": "pendientes-aro-dorado",
    "name": "Pendientes aro dorado",
    "store": "Bijoux Ramblas",
    "category": "Joyería y bisutería",
    "district": "Barceloneta",
    "price": 12.9,
    "distance": 1.25,
    "rating": 4.8,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Pendientes aro dorado product",
    "description": "Pendientes aro dorado disponible en comercio local de joyería y bisutería, con recogida cercana y stock actualizado.",
    "details": ["Joyería y bisutería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a21",
    "slug": "collar-inicial-plateado",
    "name": "Collar inicial plateado",
    "store": "Bijoux Ramblas",
    "category": "Joyería y bisutería",
    "district": "Gotico",
    "price": 29.9,
    "distance": 1.42,
    "rating": 4.9,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Collar inicial plateado product",
    "description": "Collar inicial plateado disponible en comercio local de joyería y bisutería, con recogida cercana y stock actualizado.",
    "details": ["Joyería y bisutería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a22",
    "slug": "gafas-de-sol-polarizadas",
    "name": "Gafas de sol polarizadas",
    "store": "Optica Catalunya",
    "category": "Óptica",
    "district": "Raval",
    "price": 8.95,
    "distance": 1.59,
    "rating": 4.9,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Gafas de sol polarizadas product",
    "description": "Gafas de sol polarizadas disponible en comercio local de óptica, con recogida cercana y stock actualizado.",
    "details": ["Óptica", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a23",
    "slug": "funda-rigida-para-gafas",
    "name": "Funda rígida para gafas",
    "store": "Optica Catalunya",
    "category": "Óptica",
    "district": "Born",
    "price": 27.9,
    "distance": 1.76,
    "rating": 5.0,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Funda rígida para gafas product",
    "description": "Funda rígida para gafas disponible en comercio local de óptica, con recogida cercana y stock actualizado.",
    "details": ["Óptica", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a24",
    "slug": "pack-limpieza-lentes",
    "name": "Pack limpieza lentes",
    "store": "Optica Catalunya",
    "category": "Óptica",
    "district": "Eixample",
    "price": 47.9,
    "oldPrice": 56.52,
    "distance": 1.93,
    "rating": 4.3,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Pack limpieza lentes product",
    "description": "Pack limpieza lentes disponible en comercio local de óptica, con recogida cercana y stock actualizado.",
    "details": ["Óptica", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a25",
    "slug": "perfume-viaje-citrico",
    "name": "Perfume viaje cítrico",
    "store": "Perfumeria Nova",
    "category": "Perfumería y cosmética",
    "district": "Sant Antoni",
    "price": 15.9,
    "distance": 2.1,
    "rating": 4.3,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Perfume viaje cítrico product",
    "description": "Perfume viaje cítrico disponible en comercio local de perfumería y cosmética, con recogida cercana y stock actualizado.",
    "details": ["Perfumería y cosmética", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a26",
    "slug": "crema-manos-nutritiva",
    "name": "Crema manos nutritiva",
    "store": "Perfumeria Nova",
    "category": "Perfumería y cosmética",
    "district": "Gracia",
    "price": 31.9,
    "distance": 2.27,
    "rating": 4.4,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Crema manos nutritiva product",
    "description": "Crema manos nutritiva disponible en comercio local de perfumería y cosmética, con recogida cercana y stock actualizado.",
    "details": ["Perfumería y cosmética", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a27",
    "slug": "labial-hidratante-natural",
    "name": "Labial hidratante natural",
    "store": "Perfumeria Nova",
    "category": "Perfumería y cosmética",
    "district": "Barceloneta",
    "price": 4.95,
    "distance": 2.44,
    "rating": 4.5,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Labial hidratante natural product",
    "description": "Labial hidratante natural disponible en comercio local de perfumería y cosmética, con recogida cercana y stock actualizado.",
    "details": ["Perfumería y cosmética", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a28",
    "slug": "ambientador-mikado-lavanda",
    "name": "Ambientador mikado lavanda",
    "store": "Drogueria Central",
    "category": "Droguería",
    "district": "Gotico",
    "price": 12.9,
    "distance": 0.21,
    "rating": 4.6,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Ambientador mikado lavanda product",
    "description": "Ambientador mikado lavanda disponible en comercio local de droguería, con recogida cercana y stock actualizado.",
    "details": ["Droguería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a29",
    "slug": "pack-bayetas-microfibra",
    "name": "Pack bayetas microfibra",
    "store": "Drogueria Central",
    "category": "Droguería",
    "district": "Raval",
    "price": 2.95,
    "distance": 0.38,
    "rating": 4.6,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Pack bayetas microfibra product",
    "description": "Pack bayetas microfibra disponible en comercio local de droguería, con recogida cercana y stock actualizado.",
    "details": ["Droguería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a30",
    "slug": "limpiador-multiusos-concentrado",
    "name": "Limpiador multiusos concentrado",
    "store": "Drogueria Central",
    "category": "Droguería",
    "district": "Born",
    "price": 9.95,
    "oldPrice": 11.74,
    "distance": 0.55,
    "rating": 4.7,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Limpiador multiusos concentrado product",
    "description": "Limpiador multiusos concentrado disponible en comercio local de droguería, con recogida cercana y stock actualizado.",
    "details": ["Droguería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a31",
    "slug": "mini-linterna-llavero",
    "name": "Mini linterna llavero",
    "store": "Bazar Rambla",
    "category": "Bazar multiproducto",
    "district": "Eixample",
    "price": 12.9,
    "distance": 0.72,
    "rating": 4.8,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Mini linterna llavero product",
    "description": "Mini linterna llavero disponible en comercio local de bazar multiproducto, con recogida cercana y stock actualizado.",
    "details": ["Bazar multiproducto", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a32",
    "slug": "organizador-cables-colores",
    "name": "Organizador cables colores",
    "store": "Bazar Rambla",
    "category": "Bazar multiproducto",
    "district": "Sant Antoni",
    "price": 3.95,
    "distance": 0.89,
    "rating": 4.8,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Organizador cables colores product",
    "description": "Organizador cables colores disponible en comercio local de bazar multiproducto, con recogida cercana y stock actualizado.",
    "details": ["Bazar multiproducto", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a33",
    "slug": "paraguas-plegable-compacto",
    "name": "Paraguas plegable compacto",
    "store": "Bazar Rambla",
    "category": "Bazar multiproducto",
    "district": "Gracia",
    "price": 9.95,
    "distance": 1.06,
    "rating": 4.9,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Paraguas plegable compacto product",
    "description": "Paraguas plegable compacto disponible en comercio local de bazar multiproducto, con recogida cercana y stock actualizado.",
    "details": ["Bazar multiproducto", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a34",
    "slug": "vela-aromatica-mediterranea",
    "name": "Vela aromática mediterránea",
    "store": "Casa Born Deco",
    "category": "Decoración y hogar",
    "district": "Barceloneta",
    "price": 31.9,
    "distance": 1.23,
    "rating": 5.0,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Vela aromática mediterránea product",
    "description": "Vela aromática mediterránea disponible en comercio local de decoración y hogar, con recogida cercana y stock actualizado.",
    "details": ["Decoración y hogar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a35",
    "slug": "jarron-ceramico-pequeno",
    "name": "Jarrón cerámico pequeño",
    "store": "Casa Born Deco",
    "category": "Decoración y hogar",
    "district": "Gotico",
    "price": 9.95,
    "distance": 1.4,
    "rating": 4.2,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Jarrón cerámico pequeño product",
    "description": "Jarrón cerámico pequeño disponible en comercio local de decoración y hogar, con recogida cercana y stock actualizado.",
    "details": ["Decoración y hogar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a36",
    "slug": "marco-foto-madera-natural",
    "name": "Marco foto madera natural",
    "store": "Casa Born Deco",
    "category": "Decoración y hogar",
    "district": "Raval",
    "price": 23.9,
    "oldPrice": 28.2,
    "distance": 1.57,
    "rating": 4.3,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Marco foto madera natural product",
    "description": "Marco foto madera natural disponible en comercio local de decoración y hogar, con recogida cercana y stock actualizado.",
    "details": ["Decoración y hogar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a37",
    "slug": "toalla-algodon-lavabo",
    "name": "Toalla algodón lavabo",
    "store": "Textil Sant Antoni",
    "category": "Textil hogar",
    "district": "Born",
    "price": 28.9,
    "distance": 1.74,
    "rating": 4.3,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Toalla algodón lavabo product",
    "description": "Toalla algodón lavabo disponible en comercio local de textil hogar, con recogida cercana y stock actualizado.",
    "details": ["Textil hogar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a38",
    "slug": "funda-cojin-lino-azul",
    "name": "Funda cojín lino azul",
    "store": "Textil Sant Antoni",
    "category": "Textil hogar",
    "district": "Eixample",
    "price": 42.9,
    "distance": 1.91,
    "rating": 4.4,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Funda cojín lino azul product",
    "description": "Funda cojín lino azul disponible en comercio local de textil hogar, con recogida cercana y stock actualizado.",
    "details": ["Textil hogar", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a39",
    "slug": "mesa-auxiliar-plegable",
    "name": "Mesa auxiliar plegable",
    "store": "Disseny Eixample",
    "category": "Muebles y diseño",
    "district": "Sant Antoni",
    "price": 56.5,
    "distance": 2.08,
    "rating": 4.5,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Mesa auxiliar plegable product",
    "description": "Mesa auxiliar plegable disponible en comercio local de muebles y diseño, con recogida cercana y stock actualizado.",
    "details": ["Muebles y diseño", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a40",
    "slug": "taburete-madera-bajo",
    "name": "Taburete madera bajo",
    "store": "Disseny Eixample",
    "category": "Muebles y diseño",
    "district": "Gracia",
    "price": 95.5,
    "distance": 2.25,
    "rating": 4.6,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Taburete madera bajo product",
    "description": "Taburete madera bajo disponible en comercio local de muebles y diseño, con recogida cercana y stock actualizado.",
    "details": ["Muebles y diseño", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a41",
    "slug": "cable-usb-c-reforzado",
    "name": "Cable USB-C reforzado",
    "store": "Tech Local BCN",
    "category": "Electrónica y accesorios",
    "district": "Barceloneta",
    "price": 31.9,
    "distance": 2.42,
    "rating": 4.7,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Cable USB-C reforzado product",
    "description": "Cable USB-C reforzado disponible en comercio local de electrónica y accesorios, con recogida cercana y stock actualizado.",
    "details": ["Electrónica y accesorios", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a42",
    "slug": "cargador-rapido-30w",
    "name": "Cargador rápido 30W",
    "store": "Tech Local BCN",
    "category": "Electrónica y accesorios",
    "district": "Gotico",
    "price": 9.95,
    "oldPrice": 11.74,
    "distance": 0.19,
    "rating": 4.7,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Cargador rápido 30W product",
    "description": "Cargador rápido 30W disponible en comercio local de electrónica y accesorios, con recogida cercana y stock actualizado.",
    "details": ["Electrónica y accesorios", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a43",
    "slug": "funda-movil-transparente",
    "name": "Funda móvil transparente",
    "store": "Movil Express",
    "category": "Telefonía móvil",
    "district": "Raval",
    "price": 20.9,
    "distance": 0.36,
    "rating": 4.8,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Funda móvil transparente product",
    "description": "Funda móvil transparente disponible en comercio local de telefonía móvil, con recogida cercana y stock actualizado.",
    "details": ["Telefonía móvil", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a44",
    "slug": "protector-pantalla-vidrio",
    "name": "Protector pantalla vidrio",
    "store": "Movil Express",
    "category": "Telefonía móvil",
    "district": "Born",
    "price": 29.9,
    "distance": 0.53,
    "rating": 4.9,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Protector pantalla vidrio product",
    "description": "Protector pantalla vidrio disponible en comercio local de telefonía móvil, con recogida cercana y stock actualizado.",
    "details": ["Telefonía móvil", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a45",
    "slug": "raton-inalambrico-silencioso",
    "name": "Ratón inalámbrico silencioso",
    "store": "InfoRepair Gotic",
    "category": "Informática",
    "district": "Eixample",
    "price": 16.9,
    "distance": 0.7,
    "rating": 4.9,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Ratón inalámbrico silencioso product",
    "description": "Ratón inalámbrico silencioso disponible en comercio local de informática, con recogida cercana y stock actualizado.",
    "details": ["Informática", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a46",
    "slug": "teclado-compacto-bluetooth",
    "name": "Teclado compacto bluetooth",
    "store": "InfoRepair Gotic",
    "category": "Informática",
    "district": "Sant Antoni",
    "price": 37.9,
    "distance": 0.87,
    "rating": 5.0,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Teclado compacto bluetooth product",
    "description": "Teclado compacto bluetooth disponible en comercio local de informática, con recogida cercana y stock actualizado.",
    "details": ["Informática", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a47",
    "slug": "marco-instantaneo-10x15",
    "name": "Marco instantáneo 10x15",
    "store": "Foto Born",
    "category": "Fotografía",
    "district": "Gracia",
    "price": 18.9,
    "distance": 1.04,
    "rating": 4.3,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Marco instantáneo 10x15 product",
    "description": "Marco instantáneo 10x15 disponible en comercio local de fotografía, con recogida cercana y stock actualizado.",
    "details": ["Fotografía", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a48",
    "slug": "album-fotos-artesanal",
    "name": "Álbum fotos artesanal",
    "store": "Foto Born",
    "category": "Fotografía",
    "district": "Barceloneta",
    "price": 29.9,
    "oldPrice": 35.28,
    "distance": 1.21,
    "rating": 4.4,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Álbum fotos artesanal product",
    "description": "Álbum fotos artesanal disponible en comercio local de fotografía, con recogida cercana y stock actualizado.",
    "details": ["Fotografía", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a49",
    "slug": "puzzle-barcelona-500-piezas",
    "name": "Puzzle Barcelona 500 piezas",
    "store": "Jocs i Somriures",
    "category": "Juguetería",
    "district": "Gotico",
    "price": 8.95,
    "distance": 1.38,
    "rating": 4.4,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Puzzle Barcelona 500 piezas product",
    "description": "Puzzle Barcelona 500 piezas disponible en comercio local de juguetería, con recogida cercana y stock actualizado.",
    "details": ["Juguetería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a50",
    "slug": "juego-memoria-infantil",
    "name": "Juego memoria infantil",
    "store": "Jocs i Somriures",
    "category": "Juguetería",
    "district": "Raval",
    "price": 20.9,
    "distance": 1.55,
    "rating": 4.5,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Juego memoria infantil product",
    "description": "Juego memoria infantil disponible en comercio local de juguetería, con recogida cercana y stock actualizado.",
    "details": ["Juguetería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a51",
    "slug": "maqueta-tranvia-clasico",
    "name": "Maqueta tranvía clásico",
    "store": "Modelisme BCN",
    "category": "Hobby y modelismo",
    "district": "Born",
    "price": 41.9,
    "distance": 1.72,
    "rating": 4.6,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Maqueta tranvía clásico product",
    "description": "Maqueta tranvía clásico disponible en comercio local de hobby y modelismo, con recogida cercana y stock actualizado.",
    "details": ["Hobby y modelismo", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a52",
    "slug": "set-pinturas-miniaturas",
    "name": "Set pinturas miniaturas",
    "store": "Modelisme BCN",
    "category": "Hobby y modelismo",
    "district": "Eixample",
    "price": 9.95,
    "distance": 1.89,
    "rating": 4.6,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Set pinturas miniaturas product",
    "description": "Set pinturas miniaturas disponible en comercio local de hobby y modelismo, con recogida cercana y stock actualizado.",
    "details": ["Hobby y modelismo", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a53",
    "slug": "botella-deportiva-750-ml",
    "name": "Botella deportiva 750 ml",
    "store": "Sport Local",
    "category": "Deporte",
    "district": "Sant Antoni",
    "price": 24.9,
    "distance": 2.06,
    "rating": 4.7,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Botella deportiva 750 ml product",
    "description": "Botella deportiva 750 ml disponible en comercio local de deporte, con recogida cercana y stock actualizado.",
    "details": ["Deporte", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a54",
    "slug": "banda-elastica-entrenamiento",
    "name": "Banda elástica entrenamiento",
    "store": "Sport Local",
    "category": "Deporte",
    "district": "Gracia",
    "price": 37.9,
    "oldPrice": 44.72,
    "distance": 2.23,
    "rating": 4.8,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Banda elástica entrenamiento product",
    "description": "Banda elástica entrenamiento disponible en comercio local de deporte, con recogida cercana y stock actualizado.",
    "details": ["Deporte", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a55",
    "slug": "candado-bicicleta-compacto",
    "name": "Candado bicicleta compacto",
    "store": "Bici Urbana",
    "category": "Bicicletas y movilidad urbana",
    "district": "Barceloneta",
    "price": 10.9,
    "distance": 2.4,
    "rating": 4.9,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Candado bicicleta compacto product",
    "description": "Candado bicicleta compacto disponible en comercio local de bicicletas y movilidad urbana, con recogida cercana y stock actualizado.",
    "details": ["Bicicletas y movilidad urbana", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a56",
    "slug": "luz-trasera-recargable",
    "name": "Luz trasera recargable",
    "store": "Bici Urbana",
    "category": "Bicicletas y movilidad urbana",
    "district": "Gotico",
    "price": 25.9,
    "distance": 0.17,
    "rating": 4.9,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Luz trasera recargable product",
    "description": "Luz trasera recargable disponible en comercio local de bicicletas y movilidad urbana, con recogida cercana y stock actualizado.",
    "details": ["Bicicletas y movilidad urbana", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a57",
    "slug": "correa-nylon-ajustable",
    "name": "Correa nylon ajustable",
    "store": "Mascotes Raval",
    "category": "Mascotas",
    "district": "Raval",
    "price": 24.9,
    "distance": 0.34,
    "rating": 5.0,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Correa nylon ajustable product",
    "description": "Correa nylon ajustable disponible en comercio local de mascotas, con recogida cercana y stock actualizado.",
    "details": ["Mascotas", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a58",
    "slug": "pelota-resistente-perro",
    "name": "Pelota resistente perro",
    "store": "Mascotes Raval",
    "category": "Mascotas",
    "district": "Born",
    "price": 7.95,
    "distance": 0.51,
    "rating": 4.3,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Pelota resistente perro product",
    "description": "Pelota resistente perro disponible en comercio local de mascotas, con recogida cercana y stock actualizado.",
    "details": ["Mascotas", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a59",
    "slug": "ramo-flores-secas-natural",
    "name": "Ramo flores secas natural",
    "store": "Flor Seca Barcelona",
    "category": "Floristería no perecedera",
    "district": "Eixample",
    "price": 27.9,
    "distance": 0.68,
    "rating": 4.3,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Ramo flores secas natural product",
    "description": "Ramo flores secas natural disponible en comercio local de floristería no perecedera, con recogida cercana y stock actualizado.",
    "details": ["Floristería no perecedera", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a60",
    "slug": "centro-floral-artificial",
    "name": "Centro floral artificial",
    "store": "Flor Seca Barcelona",
    "category": "Floristería no perecedera",
    "district": "Sant Antoni",
    "price": 6.95,
    "oldPrice": 8.2,
    "distance": 0.85,
    "rating": 4.4,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Centro floral artificial product",
    "description": "Centro floral artificial disponible en comercio local de floristería no perecedera, con recogida cercana y stock actualizado.",
    "details": ["Floristería no perecedera", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a61",
    "slug": "monedero-cuero-artesanal",
    "name": "Monedero cuero artesanal",
    "store": "Artesans del Gotic",
    "category": "Artesanía local",
    "district": "Gracia",
    "price": 54.5,
    "distance": 1.02,
    "rating": 4.5,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Monedero cuero artesanal product",
    "description": "Monedero cuero artesanal disponible en comercio local de artesanía local, con recogida cercana y stock actualizado.",
    "details": ["Artesanía local", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a62",
    "slug": "cuenco-ceramica-esmaltada",
    "name": "Cuenco cerámica esmaltada",
    "store": "Artesans del Gotic",
    "category": "Artesanía local",
    "district": "Barceloneta",
    "price": 27.9,
    "distance": 1.19,
    "rating": 4.5,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Cuenco cerámica esmaltada product",
    "description": "Cuenco cerámica esmaltada disponible en comercio local de artesanía local, con recogida cercana y stock actualizado.",
    "details": ["Artesanía local", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a63",
    "slug": "lamina-ilustrada-born",
    "name": "Lámina ilustrada Born",
    "store": "Galeria Mini Art",
    "category": "Galerías y arte",
    "district": "Gotico",
    "price": 61.5,
    "distance": 1.36,
    "rating": 4.6,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Lámina ilustrada Born product",
    "description": "Lámina ilustrada Born disponible en comercio local de galerías y arte, con recogida cercana y stock actualizado.",
    "details": ["Galerías y arte", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a64",
    "slug": "print-numerado-barcelona",
    "name": "Print numerado Barcelona",
    "store": "Galeria Mini Art",
    "category": "Galerías y arte",
    "district": "Raval",
    "price": 90.5,
    "distance": 1.53,
    "rating": 4.7,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Print numerado Barcelona product",
    "description": "Print numerado Barcelona disponible en comercio local de galerías y arte, con recogida cercana y stock actualizado.",
    "details": ["Galerías y arte", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a65",
    "slug": "puas-guitarra-pack-12",
    "name": "Púas guitarra pack 12",
    "store": "Vinils & Music",
    "category": "Música",
    "district": "Born",
    "price": 22.9,
    "distance": 1.7,
    "rating": 4.8,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Púas guitarra pack 12 product",
    "description": "Púas guitarra pack 12 disponible en comercio local de música, con recogida cercana y stock actualizado.",
    "details": ["Música", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a66",
    "slug": "vinilo-jazz-clasico",
    "name": "Vinilo jazz clásico",
    "store": "Vinils & Music",
    "category": "Música",
    "district": "Eixample",
    "price": 38.9,
    "oldPrice": 45.9,
    "distance": 1.87,
    "rating": 4.8,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Vinilo jazz clásico product",
    "description": "Vinilo jazz clásico disponible en comercio local de música, con recogida cercana y stock actualizado.",
    "details": ["Música", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a67",
    "slug": "caja-botones-surtidos",
    "name": "Caja botones surtidos",
    "store": "Merceria Ramblas",
    "category": "Mercería",
    "district": "Sant Antoni",
    "price": 3.95,
    "distance": 2.04,
    "rating": 4.9,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Caja botones surtidos product",
    "description": "Caja botones surtidos disponible en comercio local de mercería, con recogida cercana y stock actualizado.",
    "details": ["Mercería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a68",
    "slug": "hilo-algodon-colores",
    "name": "Hilo algodón colores",
    "store": "Merceria Ramblas",
    "category": "Mercería",
    "district": "Gracia",
    "price": 8.95,
    "distance": 2.21,
    "rating": 5.0,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Hilo algodón colores product",
    "description": "Hilo algodón colores disponible en comercio local de mercería, con recogida cercana y stock actualizado.",
    "details": ["Mercería", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a69",
    "slug": "parche-termoadhesivo-denim",
    "name": "Parche termoadhesivo denim",
    "store": "Arreglos Express",
    "category": "Costura y arreglos",
    "district": "Barceloneta",
    "price": 17.9,
    "distance": 2.38,
    "rating": 4.2,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Parche termoadhesivo denim product",
    "description": "Parche termoadhesivo denim disponible en comercio local de costura y arreglos, con recogida cercana y stock actualizado.",
    "details": ["Costura y arreglos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a70",
    "slug": "kit-costura-viaje",
    "name": "Kit costura viaje",
    "store": "Arreglos Express",
    "category": "Costura y arreglos",
    "district": "Gotico",
    "price": 5.95,
    "distance": 0.15,
    "rating": 4.3,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Kit costura viaje product",
    "description": "Kit costura viaje disponible en comercio local de costura y arreglos, con recogida cercana y stock actualizado.",
    "details": ["Costura y arreglos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a71",
    "slug": "camisa-vintage-cuadros",
    "name": "Camisa vintage cuadros",
    "store": "Vintage Born",
    "category": "Segunda mano y vintage",
    "district": "Raval",
    "price": 31.9,
    "distance": 0.32,
    "rating": 4.3,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Camisa vintage cuadros product",
    "description": "Camisa vintage cuadros disponible en comercio local de segunda mano y vintage, con recogida cercana y stock actualizado.",
    "details": ["Segunda mano y vintage", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a72",
    "slug": "libro-usado-edicion-clasica",
    "name": "Libro usado edición clásica",
    "store": "Vintage Born",
    "category": "Segunda mano y vintage",
    "district": "Born",
    "price": 54.5,
    "oldPrice": 64.31,
    "distance": 0.49,
    "rating": 4.4,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Libro usado edición clásica product",
    "description": "Libro usado edición clásica disponible en comercio local de segunda mano y vintage, con recogida cercana y stock actualizado.",
    "details": ["Segunda mano y vintage", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a73",
    "slug": "caja-decorativa-antigua",
    "name": "Caja decorativa antigua",
    "store": "Antic Gotic",
    "category": "Antigüedades",
    "district": "Eixample",
    "price": 96.5,
    "distance": 0.66,
    "rating": 4.5,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Caja decorativa antigua product",
    "description": "Caja decorativa antigua disponible en comercio local de antigüedades, con recogida cercana y stock actualizado.",
    "details": ["Antigüedades", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a74",
    "slug": "espejo-sobremesa-vintage",
    "name": "Espejo sobremesa vintage",
    "store": "Antic Gotic",
    "category": "Antigüedades",
    "district": "Sant Antoni",
    "price": 34.9,
    "distance": 0.83,
    "rating": 4.6,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Espejo sobremesa vintage product",
    "description": "Espejo sobremesa vintage disponible en comercio local de antigüedades, con recogida cercana y stock actualizado.",
    "details": ["Antigüedades", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a75",
    "slug": "marco-negro-30x40",
    "name": "Marco negro 30x40",
    "store": "Marcs Barcelona",
    "category": "Enmarcación",
    "district": "Gracia",
    "price": 18.9,
    "distance": 1.0,
    "rating": 4.6,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Marco negro 30x40 product",
    "description": "Marco negro 30x40 disponible en comercio local de enmarcación, con recogida cercana y stock actualizado.",
    "details": ["Enmarcación", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a76",
    "slug": "passepartout-blanco-a3",
    "name": "Passepartout blanco A3",
    "store": "Marcs Barcelona",
    "category": "Enmarcación",
    "district": "Barceloneta",
    "price": 35.9,
    "distance": 1.17,
    "rating": 4.7,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Passepartout blanco A3 product",
    "description": "Passepartout blanco A3 disponible en comercio local de enmarcación, con recogida cercana y stock actualizado.",
    "details": ["Enmarcación", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a77",
    "slug": "encuadernacion-espiral-a4",
    "name": "Encuadernación espiral A4",
    "store": "Copy Rambla",
    "category": "Copistería e impresión",
    "district": "Gotico",
    "price": 24.9,
    "distance": 1.34,
    "rating": 4.8,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Encuadernación espiral A4 product",
    "description": "Encuadernación espiral A4 disponible en comercio local de copistería e impresión, con recogida cercana y stock actualizado.",
    "details": ["Copistería e impresión", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a78",
    "slug": "impresion-lamina-color",
    "name": "Impresión lámina color",
    "store": "Copy Rambla",
    "category": "Copistería e impresión",
    "district": "Raval",
    "price": 1.95,
    "oldPrice": 2.3,
    "distance": 1.51,
    "rating": 4.9,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Impresión lámina color product",
    "description": "Impresión lámina color disponible en comercio local de copistería e impresión, con recogida cercana y stock actualizado.",
    "details": ["Copistería e impresión", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a79",
    "slug": "aftercare-piercing-30ml",
    "name": "Aftercare piercing 30ml",
    "store": "Piercing Studio Shop",
    "category": "Tatuaje y piercing retail",
    "district": "Born",
    "price": 20.9,
    "distance": 1.68,
    "rating": 4.9,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Aftercare piercing 30ml product",
    "description": "Aftercare piercing 30ml disponible en comercio local de tatuaje y piercing retail, con recogida cercana y stock actualizado.",
    "details": ["Tatuaje y piercing retail", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a80",
    "slug": "aro-piercing-acero",
    "name": "Aro piercing acero",
    "store": "Piercing Studio Shop",
    "category": "Tatuaje y piercing retail",
    "district": "Eixample",
    "price": 34.9,
    "distance": 1.85,
    "rating": 5.0,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Aro piercing acero product",
    "description": "Aro piercing acero disponible en comercio local de tatuaje y piercing retail, con recogida cercana y stock actualizado.",
    "details": ["Tatuaje y piercing retail", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a81",
    "slug": "sellos-nacionales-pack",
    "name": "Sellos nacionales pack",
    "store": "Estanc del Centre",
    "category": "Estancos y loterías",
    "district": "Sant Antoni",
    "price": 4.95,
    "distance": 2.02,
    "rating": 4.2,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Sellos nacionales pack product",
    "description": "Sellos nacionales pack disponible en comercio local de estancos y loterías, con recogida cercana y stock actualizado.",
    "details": ["Estancos y loterías", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a82",
    "slug": "prensa-semanal-local",
    "name": "Prensa semanal local",
    "store": "Estanc del Centre",
    "category": "Estancos y loterías",
    "district": "Gracia",
    "price": 8.95,
    "distance": 2.19,
    "rating": 4.3,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Prensa semanal local product",
    "description": "Prensa semanal local disponible en comercio local de estancos y loterías, con recogida cercana y stock actualizado.",
    "details": ["Estancos y loterías", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a83",
    "slug": "vela-ritual-blanca",
    "name": "Vela ritual blanca",
    "store": "Aura Esoterica",
    "category": "Productos esotéricos",
    "district": "Barceloneta",
    "price": 10.9,
    "distance": 2.36,
    "rating": 4.4,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Vela ritual blanca product",
    "description": "Vela ritual blanca disponible en comercio local de productos esotéricos, con recogida cercana y stock actualizado.",
    "details": ["Productos esotéricos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a84",
    "slug": "incienso-sandalo-natural",
    "name": "Incienso sándalo natural",
    "store": "Aura Esoterica",
    "category": "Productos esotéricos",
    "district": "Gotico",
    "price": 21.9,
    "oldPrice": 25.84,
    "distance": 0.13,
    "rating": 4.4,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Incienso sándalo natural product",
    "description": "Incienso sándalo natural disponible en comercio local de productos esotéricos, con recogida cercana y stock actualizado.",
    "details": ["Productos esotéricos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a85",
    "slug": "manga-tomo-1-popular",
    "name": "Manga tomo 1 popular",
    "store": "Manga Gotic",
    "category": "Tiendas de cómic y manga",
    "district": "Raval",
    "price": 21.9,
    "distance": 0.3,
    "rating": 4.5,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Manga tomo 1 popular product",
    "description": "Manga tomo 1 popular disponible en comercio local de tiendas de cómic y manga, con recogida cercana y stock actualizado.",
    "details": ["Tiendas de cómic y manga", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a86",
    "slug": "figura-coleccionable-heroe",
    "name": "Figura coleccionable héroe",
    "store": "Manga Gotic",
    "category": "Tiendas de cómic y manga",
    "district": "Born",
    "price": 37.9,
    "distance": 0.47,
    "rating": 4.6,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Figura coleccionable héroe product",
    "description": "Figura coleccionable héroe disponible en comercio local de tiendas de cómic y manga, con recogida cercana y stock actualizado.",
    "details": ["Tiendas de cómic y manga", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a87",
    "slug": "mando-consola-compatible",
    "name": "Mando consola compatible",
    "store": "Game Local BCN",
    "category": "Gaming y videojuegos",
    "district": "Eixample",
    "price": 48.9,
    "distance": 0.64,
    "rating": 4.7,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Mando consola compatible product",
    "description": "Mando consola compatible disponible en comercio local de gaming y videojuegos, con recogida cercana y stock actualizado.",
    "details": ["Gaming y videojuegos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a88",
    "slug": "funda-cartuchos-portatil",
    "name": "Funda cartuchos portátil",
    "store": "Game Local BCN",
    "category": "Gaming y videojuegos",
    "district": "Sant Antoni",
    "price": 70.5,
    "distance": 0.81,
    "rating": 4.8,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Funda cartuchos portátil product",
    "description": "Funda cartuchos portátil disponible en comercio local de gaming y videojuegos, con recogida cercana y stock actualizado.",
    "details": ["Gaming y videojuegos", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a89",
    "slug": "cepillo-termico-profesional",
    "name": "Cepillo térmico profesional",
    "store": "Beauty Pro Shop",
    "category": "Belleza profesional",
    "district": "Gracia",
    "price": 17.9,
    "distance": 0.98,
    "rating": 4.8,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Cepillo térmico profesional product",
    "description": "Cepillo térmico profesional disponible en comercio local de belleza profesional, con recogida cercana y stock actualizado.",
    "details": ["Belleza profesional", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a90",
    "slug": "esmalte-unas-gel",
    "name": "Esmalte uñas gel",
    "store": "Beauty Pro Shop",
    "category": "Belleza profesional",
    "district": "Barceloneta",
    "price": 33.9,
    "oldPrice": 40.0,
    "distance": 1.15,
    "rating": 4.9,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Esmalte uñas gel product",
    "description": "Esmalte uñas gel disponible en comercio local de belleza profesional, con recogida cercana y stock actualizado.",
    "details": ["Belleza profesional", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a91",
    "slug": "munequera-elastica-soporte",
    "name": "Muñequera elástica soporte",
    "store": "Ortopedia Catalunya",
    "category": "Ortopedia",
    "district": "Gotico",
    "price": 33.9,
    "distance": 1.32,
    "rating": 5.0,
    "stock": 13,
    "pickup": "15 min",
    "imageQuery": "Muñequera elástica soporte product",
    "description": "Muñequera elástica soporte disponible en comercio local de ortopedia, con recogida cercana y stock actualizado.",
    "details": ["Ortopedia", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a92",
    "slug": "plantilla-ortopedica-basica",
    "name": "Plantilla ortopédica básica",
    "store": "Ortopedia Catalunya",
    "category": "Ortopedia",
    "district": "Raval",
    "price": 56.5,
    "distance": 1.49,
    "rating": 4.3,
    "stock": 20,
    "pickup": "20 min",
    "imageQuery": "Plantilla ortopédica básica product",
    "description": "Plantilla ortopédica básica disponible en comercio local de ortopedia, con recogida cercana y stock actualizado.",
    "details": ["Ortopedia", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a93",
    "slug": "tensiometro-brazo-digital",
    "name": "Tensiómetro brazo digital",
    "store": "Salud Hogar BCN",
    "category": "Material sanitario no farmacéutico",
    "district": "Born",
    "price": 60.5,
    "distance": 1.66,
    "rating": 4.3,
    "stock": 27,
    "pickup": "25 min",
    "imageQuery": "Tensiómetro brazo digital product",
    "description": "Tensiómetro brazo digital disponible en comercio local de material sanitario no farmacéutico, con recogida cercana y stock actualizado.",
    "details": ["Material sanitario no farmacéutico", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a94",
    "slug": "botiquin-basico-hogar",
    "name": "Botiquín básico hogar",
    "store": "Salud Hogar BCN",
    "category": "Material sanitario no farmacéutico",
    "district": "Eixample",
    "price": 22.9,
    "distance": 1.83,
    "rating": 4.4,
    "stock": 34,
    "pickup": "30 min",
    "imageQuery": "Botiquín básico hogar product",
    "description": "Botiquín básico hogar disponible en comercio local de material sanitario no farmacéutico, con recogida cercana y stock actualizado.",
    "details": ["Material sanitario no farmacéutico", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a95",
    "slug": "taza-personalizada-nombre",
    "name": "Taza personalizada nombre",
    "store": "Personaliza BCN",
    "category": "Regalos personalizados",
    "district": "Sant Antoni",
    "price": 25.9,
    "distance": 2.0,
    "rating": 4.5,
    "stock": 41,
    "pickup": "35 min",
    "imageQuery": "Taza personalizada nombre product",
    "description": "Taza personalizada nombre disponible en comercio local de regalos personalizados, con recogida cercana y stock actualizado.",
    "details": ["Regalos personalizados", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a96",
    "slug": "camiseta-impresion-local",
    "name": "Camiseta impresión local",
    "store": "Personaliza BCN",
    "category": "Regalos personalizados",
    "district": "Gracia",
    "price": 7.9,
    "oldPrice": 9.32,
    "distance": 2.17,
    "rating": 4.6,
    "stock": 48,
    "pickup": "40 min",
    "imageQuery": "Camiseta impresión local product",
    "description": "Camiseta impresión local disponible en comercio local de regalos personalizados, con recogida cercana y stock actualizado.",
    "details": ["Regalos personalizados", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a97",
    "slug": "plato-ceramica-artesanal",
    "name": "Plato cerámica artesanal",
    "store": "Ceramica Local",
    "category": "Cerámica y diseño local",
    "district": "Barceloneta",
    "price": 42.9,
    "distance": 2.34,
    "rating": 4.6,
    "stock": 55,
    "pickup": "45 min",
    "imageQuery": "Plato cerámica artesanal product",
    "description": "Plato cerámica artesanal disponible en comercio local de cerámica y diseño local, con recogida cercana y stock actualizado.",
    "details": ["Cerámica y diseño local", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a98",
    "slug": "azulejo-decorativo-barcelona",
    "name": "Azulejo decorativo Barcelona",
    "store": "Ceramica Local",
    "category": "Cerámica y diseño local",
    "district": "Gotico",
    "price": 21.9,
    "distance": 2.51,
    "rating": 4.7,
    "stock": 62,
    "pickup": "50 min",
    "imageQuery": "Azulejo decorativo Barcelona product",
    "description": "Azulejo decorativo Barcelona disponible en comercio local de cerámica y diseño local, con recogida cercana y stock actualizado.",
    "details": ["Cerámica y diseño local", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a99",
    "slug": "mochila-urbana-ligera",
    "name": "Mochila urbana ligera",
    "store": "Travel Shop Rambla",
    "category": "Maletas y viaje",
    "district": "Raval",
    "price": 42.9,
    "distance": 0.28,
    "rating": 4.7,
    "stock": 69,
    "pickup": "55 min",
    "imageQuery": "Mochila urbana ligera product",
    "description": "Mochila urbana ligera disponible en comercio local de maletas y viaje, con recogida cercana y stock actualizado.",
    "details": ["Maletas y viaje", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  },
  {
    "id": "a100",
    "slug": "neceser-viaje-impermeable",
    "name": "Neceser viaje impermeable",
    "store": "Travel Shop Rambla",
    "category": "Maletas y viaje",
    "district": "Born",
    "price": 5.95,
    "distance": 0.45,
    "rating": 4.8,
    "stock": 6,
    "pickup": "10 min",
    "imageQuery": "Neceser viaje impermeable product",
    "description": "Neceser viaje impermeable disponible en comercio local de maletas y viaje, con recogida cercana y stock actualizado.",
    "details": ["Maletas y viaje", "Comercio local verificado", "Recogida en tienda", "Stock disponible"]
  }
] as const;

const additionalProducts: MarketplaceProduct[] = additionalProductSeeds.map((product, index) => ({
  id: product.id,
  slug: product.slug,
  name: product.name,
  store: product.store,
  category: product.category,
  district: product.district,
  price: product.price,
  oldPrice: product.oldPrice,
  distance: product.distance,
  rating: product.rating,
  stock: product.stock,
  pickup: product.pickup,
  imageUrl: imageFor(product.imageQuery, index + 300),
  description: product.description,
  details: [...product.details]
}));

export const marketplaceProducts: MarketplaceProduct[] = [...baseProducts, ...additionalProducts];

export { marketplaceCategories };

export function money(value: number) {
  return new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(value);
}
