"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, CreditCard, Home, KeyRound, Lock, MapPin, Package, RotateCcw, ShieldCheck, Star, Ticket, Truck, UserRound, X } from "lucide-react";
import { dict, getInitialLang, setStoredLang, type Lang } from "@/lib/i18n";

type User = { name: string; email: string };
type StoredOrderItem = { id?: string; name: string; quantity: number; price?: number; store: string };
type StoredOrder = { id: string; status: string; store: string; total: string; pickup: string; date: string; items?: StoredOrderItem[] };

const fallbackOrders: StoredOrder[] = [
  { id: "GO-1024", status: "Listo para recoger", store: "Ferreteria Ramblas Pro", total: "12,45 €", pickup: "GO-1024", date: "29/04/2026", items: [{ name: "Pinzas pequenas metalicas pack 12", quantity: 2, store: "Ferreteria Ramblas Pro" }, { name: "Kit reforma rapida", quantity: 1, store: "Ferreteria Ramblas Pro" }] },
  { id: "GO-1023", status: "Entregado", store: "DulceRaval", total: "8,90 €", pickup: "GO-1023", date: "26/04/2026", items: [{ name: "Anillo de caramelo sabor fresa", quantity: 3, store: "DulceRaval" }] }
];

function LangToggle({ lang, setLang }: { lang: Lang; setLang: (lang: Lang) => void }) { function change(next: Lang) { setLang(next); setStoredLang(next); } return <div className="flex items-center gap-1 rounded-full bg-white/10 p-1"><button onClick={() => change("es")} className={`rounded-full px-2 py-1 text-base ${lang === "es" ? "grayscale opacity-40" : "opacity-100"}`}>🇪🇸</button><button onClick={() => change("ca")} className={`rounded-full px-2 py-1 text-xs font-black text-caixa-yellow ${lang === "ca" ? "grayscale opacity-40" : "opacity-100"}`}>CAT</button></div>; }
function Card({ title, icon: Icon, children }: { title: string; icon: any; children: React.ReactNode }) { return <article className="rounded-3xl bg-white p-6 shadow-soft"><div className="mb-4 flex items-center gap-3"><div className="rounded-2xl bg-caixa-sky p-3 text-caixa-blue"><Icon className="h-6 w-6" /></div><h2 className="text-2xl font-black text-caixa-ink">{title}</h2></div>{children}</article>; }

export default function UserPortalPage() {
  const [lang, setLang] = useState<Lang>("es");
  const t = dict[lang];
  const [user, setUser] = useState<User>({ name: "Cliente", email: "cliente@faciliteago.com" });
  const [orders, setOrders] = useState<StoredOrder[]>(fallbackOrders);
  const [selectedOrder, setSelectedOrder] = useState<StoredOrder | null>(null);

  useEffect(() => { const initialLang = getInitialLang(); setLang(initialLang); const savedUser = window.localStorage.getItem("faciliteago-user"); const savedOrders = window.localStorage.getItem("faciliteago-orders"); if (savedUser) setUser(JSON.parse(savedUser)); if (savedOrders) { const parsed = JSON.parse(savedOrders); setOrders(parsed.length ? parsed : fallbackOrders); } }, []);

  return (
    <main className="min-h-screen bg-caixa-sky px-5 py-8">
      <section className="mx-auto max-w-7xl">
        <header className="mb-8 flex flex-col justify-between gap-4 rounded-[2rem] bg-caixa-navy p-7 text-white shadow-soft md:flex-row md:items-center">
          <div><a href="/" className="text-sm font-bold text-blue-100">← {t.backMarketplace}</a><p className="mt-4 text-sm font-bold uppercase tracking-[0.25em] text-caixa-yellow">{t.accountArea}</p><h1 className="mt-2 text-4xl font-black">{t.myAccount}</h1><p className="mt-3 max-w-2xl text-blue-100">{t.accountText}</p></div>
          <div className="flex items-center gap-3"><LangToggle lang={lang} setLang={setLang} /><div className="rounded-3xl bg-white/10 p-5"><UserRound className="h-10 w-10 text-caixa-yellow" /><p className="mt-3 font-black">{user.name}</p><p className="text-sm text-blue-100">{user.email}</p></div></div>
        </header>
        <div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="grid gap-6">
            <Card title={t.mainAddress} icon={Home}><div className="space-y-3 text-sm font-semibold text-slate-600"><p className="font-black text-caixa-navy">Carrer de la Portaferrissa 12, 08002 Barcelona</p><p>{t.addressReference}</p><p className="flex items-center gap-2 text-caixa-blue"><MapPin className="h-4 w-4" /> {t.activeLocation}</p><button className="rounded-2xl bg-caixa-blue px-4 py-2 font-bold text-white">{t.editAddress}</button></div></Card>
            <Card title={t.paymentMethod} icon={CreditCard}><div className="space-y-3 text-sm font-semibold text-slate-600"><p className="font-black text-caixa-navy">{t.paymentCard}</p><p>{t.protectedPurchase}</p><button className="rounded-2xl bg-caixa-blue px-4 py-2 font-bold text-white">{t.changeMethod}</button></div></Card>
            <Card title={t.preferredShipping} icon={Truck}><div className="space-y-3 text-sm font-semibold text-slate-600"><p className="font-black text-caixa-navy">{t.clickCollect}</p><p>{t.pickupPriority}</p><div className="grid gap-2"><label className="rounded-2xl bg-blue-50 px-4 py-3"><input type="radio" defaultChecked className="mr-2" /> {t.storePickup}</label><label className="rounded-2xl bg-blue-50 px-4 py-3"><input type="radio" className="mr-2" /> {t.localDelivery}</label></div></div></Card>
            <Card title={t.security} icon={ShieldCheck}><div className="grid gap-3 text-sm font-semibold text-slate-600"><button className="flex items-center gap-2 rounded-2xl bg-blue-50 px-4 py-3 text-left font-bold text-caixa-navy"><KeyRound className="h-4 w-4" /> {t.changePassword}</button><button className="flex items-center gap-2 rounded-2xl bg-blue-50 px-4 py-3 text-left font-bold text-caixa-navy"><Lock className="h-4 w-4" /> {t.twoFactor}</button><button className="rounded-2xl bg-white px-4 py-3 text-left font-bold text-caixa-navy ring-1 ring-blue-100">{t.closeSessions}</button></div></Card>
          </div>
          <div className="grid gap-6">
            <Card title={t.summary} icon={CheckCircle2}><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-3xl font-black text-caixa-blue">{orders.length}</p><p className="text-sm font-bold text-slate-500">{t.orders}</p></div><div className="rounded-2xl bg-blue-50 p-4"><p className="text-3xl font-black text-caixa-blue">38,40 €</p><p className="text-sm font-bold text-slate-500">{t.savings}</p></div><div className="rounded-2xl bg-blue-50 p-4"><p className="text-3xl font-black text-caixa-blue">7</p><p className="text-sm font-bold text-slate-500">{t.stores}</p></div></div></Card>
            <Card title={t.orders} icon={Package}><div className="grid gap-4">{orders.length === 0 ? <article className="rounded-3xl border border-blue-100 bg-white p-5"><p className="text-lg font-bold text-slate-600">{t.noOrders}</p></article> : orders.map((order) => <article key={order.id} className="rounded-3xl border border-blue-100 bg-white p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm font-bold text-slate-500">{t.order} {order.id} · {order.date}</p><h3 className="text-2xl font-black text-caixa-ink">{order.store}</h3><p className="mt-1 font-bold text-caixa-blue">{order.status} · {order.total}</p>{order.items && <p className="mt-2 text-sm font-semibold text-slate-500">{order.items.map((item) => `${item.quantity}x ${item.name}`).join(" · ")}</p>}</div><div className="rounded-2xl bg-caixa-sky px-5 py-4 text-center"><p className="text-xs font-bold text-slate-500">{t.pickupCode}</p><p className="text-2xl font-black text-caixa-navy">{order.pickup}</p></div></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={() => setSelectedOrder(order)} className="flex items-center gap-2 rounded-full bg-caixa-blue px-4 py-2 text-sm font-bold text-white"><Package className="h-4 w-4" /> {t.seeDetail}</button><button className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-caixa-navy ring-1 ring-blue-100"><RotateCcw className="h-4 w-4" /> {t.returnOrder}</button><button className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-caixa-navy ring-1 ring-blue-100"><Ticket className="h-4 w-4" /> {t.issue}</button><button className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-caixa-navy ring-1 ring-blue-100"><Star className="h-4 w-4" /> {t.review}</button></div></article>)}</div></Card>
          </div>
        </div>
      </section>
      {selectedOrder && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><article className="w-full max-w-2xl rounded-[2rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-slate-500">{t.order} {selectedOrder.id} · {selectedOrder.date}</p><h2 className="mt-1 text-3xl font-black text-caixa-navy">{t.orderDetail}</h2><p className="mt-2 font-bold text-caixa-blue">{selectedOrder.status} · {selectedOrder.total}</p></div><button onClick={() => setSelectedOrder(null)} className="rounded-full bg-blue-50 p-2 text-caixa-navy"><X className="h-5 w-5" /></button></div><div className="mt-6 grid gap-3 rounded-3xl bg-caixa-sky p-4 md:grid-cols-3"><div><p className="text-xs font-bold text-slate-500">{t.commerce}</p><p className="font-black text-caixa-navy">{selectedOrder.store}</p></div><div><p className="text-xs font-bold text-slate-500">{t.pickup}</p><p className="font-black text-caixa-navy">{selectedOrder.pickup}</p></div><div><p className="text-xs font-bold text-slate-500">{t.delivery}</p><p className="font-black text-caixa-navy">Click & collect</p></div></div><div className="mt-6"><h3 className="text-xl font-black text-caixa-ink">{t.products}</h3><div className="mt-3 grid gap-3">{(selectedOrder.items?.length ? selectedOrder.items : [{ name: "Producto local", quantity: 1, store: selectedOrder.store }]).map((item, index) => <div key={`${item.name}-${index}`} className="flex justify-between rounded-2xl border border-blue-100 px-4 py-3 text-sm font-bold"><span>{item.quantity}x {item.name}</span><span className="text-slate-500">{item.store}</span></div>)}</div></div><div className="mt-6 flex justify-end"><button onClick={() => setSelectedOrder(null)} className="rounded-2xl bg-caixa-blue px-5 py-3 font-black text-white">{t.closeDetail}</button></div></article></div>}
    </main>
  );
}
